/**
 * Merge metals-raw.json with curated encyclopedia narratives and source metadata.
 * Run: node scripts/build-metals.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { NARRATIVES } from "./narratives.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const rawPath = path.join(root, "src/data/metals-raw.json");
const outPath = path.join(root, "src/data/metals.js");

const PROPERTY_SOURCES = [
  {
    id: "pubchem-ptable",
    title: "PubChem Periodic Table CSV",
    url: "https://pubchem.ncbi.nlm.nih.gov/rest/pug/periodictable/CSV",
    tier: 1
  },
  {
    id: "periodictable-com",
    title: "PeriodicTable.com / Wolfram ElementData (conductivity, hardness, abundance)",
    url: "https://periodictable.com/",
    tier: 2
  },
  {
    id: "wikimedia-commons",
    title: "Wikimedia Commons sample images",
    url: "https://commons.wikimedia.org/",
    tier: 2
  }
];

/** Build the metals.js file contents (does not write). */
export function generateMetalsFile() {
  const raw = JSON.parse(fs.readFileSync(rawPath, "utf8"));
  const missing = [];

  const metals = raw.map((metal) => {
    const narrative = NARRATIVES[metal.key];
    if (!narrative) {
      missing.push(metal.key);
    }

    const entry = narrative || {
      overview: `${metal.name} (${metal.symbol}) is a ${metal.family.toLowerCase()} element in this metals reference set.`,
      production: "Industrial or laboratory production route not yet curated for this entry.",
      uses: "Uses not yet curated for this entry.",
      commodityNotes: null,
      notableFacts: [],
      narrativeConfidence: "unverified-model",
      narrativeSources: []
    };

    return {
      ...metal,
      summary: entry.overview,
      overview: entry.overview,
      production: entry.production,
      uses: entry.uses,
      commodityNotes: entry.commodityNotes || null,
      notableFacts: entry.notableFacts || [],
      narrativeConfidence: entry.narrativeConfidence || "unverified-model",
      narrativeSources: entry.narrativeSources || [],
      propertySources: PROPERTY_SOURCES,
      pubchemUrl: `https://pubchem.ncbi.nlm.nih.gov/element/${encodeURIComponent(metal.name)}`,
      // Reserved for a future Three.js / Babylon mount without reshaping the schema.
      viewer: {
        physicalSample: {
          enabled: false,
          materialHint: metal.family,
          density: metal.density
        },
        atomicModel: {
          enabled: false,
          atomicNumber: metal.atomicNumber,
          electronConfiguration: metal.electronConfiguration
        }
      }
    };
  });

  if (missing.length) {
    console.warn("Missing curated narratives:", missing.join(", "));
  }

  return {
    metals,
    file: `/** Auto-generated by scripts/build-metals.mjs — do not edit by hand. */\nexport const metals = ${JSON.stringify(metals, null, 2)};\nexport default metals;\n`
  };
}

export function writeMetalsFile() {
  const { metals, file } = generateMetalsFile();
  fs.writeFileSync(outPath, file);
  console.log(`Wrote ${metals.length} metals to ${path.relative(root, outPath)}`);
  return outPath;
}

const isMain =
  process.argv[1] && path.basename(process.argv[1]).replace(/\\/g, "/") === "build-metals.mjs";
if (isMain) {
  writeMetalsFile();
}
